### PR TITLE
Add syntax highlighting hints and apply R stdout style

### PR DESCRIPTION
**Pull request by matthewfeickert**
It is isn't as obvious what is stdout and what is input and that this style change, which is common in the R community, makes this clear. Adding syntax highlighting make this even more clean as it makes things pop out a bit more. :+1:

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@RaoOfPhysics I think this is the only instance of output from a command in the `README`, and this should now address your very good comment. :+1:

**Comment by RaoOfPhysics** [comment]
Looks good to me!

I might propose a PR that explicitly marks out which statements need to be executed in the shell and which ones within R. I can also modify the fenced codeblocks with the syntax highlighting for the code:

````markdown
```r
packrat::status()
```
````

or

````markdown
```sh
R -e 'install.packages("packrat")'
```
````

**Review by RaoOfPhysics — APPROVED** [review]

**Comment by matthewfeickert** [comment]
Ah great! I didn't know that the R syntax highlighting was available on GitHub. Yeah, given that this PR is so minimial (1 line) I might as well just revise this to be an R style PR. As this

```r
packrat::status()
```

```sh
R -e 'install.packages("packrat")'
```

obviously looks nicer. :)

**Comment by RaoOfPhysics** [comment]
Works for me! And makes my life simpler. ;)

**Review by RaoOfPhysics — APPROVED** [review]
The final README looks beautiful. <3 Thanks for taking on board the suggestion!

**Comment by matthewfeickert** [comment]
@RaoOfPhysics Thanks for making a great point and providing really helpful feedback! :+1:

**Pull request merged**
